---
- name: Configure macOS settings
  hosts: localhost
  tasks:
    # Get the executing user's username
    - name: Get executing user's username
      command: whoami
      register: executing_user
      changed_when: false

    # Ensure bash is listed in /etc/shells
    - name: Ensure bash is in /etc/shells
      lineinfile:
        path: /etc/shells
        line: '/bin/bash'
        state: present
      become: true

    # Change default shell to bash for the executing user
    - name: Set bash as the default shell for executing user
      command: "chsh -s /bin/bash {{ executing_user.stdout }}"
      become: true

    # Check if Homebrew is installed
    - name: Check if Homebrew is installed
      command: which brew
      register: brew_check
      failed_when: false
      changed_when: false

    # Install Homebrew if not installed
    - name: Install Homebrew
      shell: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | /bin/bash
      when: brew_check.rc != 0
      become: false

    - name: Install Casks
      command:
        cmd: "brew install --cask {{ item }}"
      loop:
        - google-chrome
        - iterm2
        - visual-studio-code
        - dbeaver-community
