---
- name: Configure macOS settings
  hosts: localhost
  tasks:
    # Get the executing user's username
    - name: Get executing user's username
      command: whoami
      register: executing_user
      changed_when: false

    # Ensure bash is listed in /etc/shells
    - name: Ensure bash is in /etc/shells
      lineinfile:
        path: /etc/shells
        line: '/bin/bash'
        state: present
      become: true

    # Change default shell to bash for the executing user
    - name: Set bash as the default shell for executing user
      command: "chsh -s /bin/bash {{ executing_user.stdout }}"
      become: true

    # Ensure ~/.bash_profile exists
    - name: Ensure ~/.bash_profile exists
      copy:
        dest: "~/{{ executing_user.stdout }}/.bash_profile"
        content: |
          export CLICOLOR=1
          export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
          export PATH="/usr/local/bin:$PATH"
          export BASH_SILENCE_DEPRECATION_WARNING=1
          alias ll='ls -ltr'
          eval "$(/opt/homebrew/bin/brew shellenv)"
          export test='hi'
        force: no
      become: false

    # Ensure desired contents in ~/.bash_profile
    - name: Ensure desired contents in ~/.bash_profile
      lineinfile:
        path: "~/{{ executing_user.stdout }}/.bash_profile"
        line: "{{ item }}"
      loop:
        - "export CLICOLOR=1"
        - "export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd"
        - "export PATH=\"/usr/local/bin:$PATH\""
        - "export BASH_SILENCE_DEPRECATION_WARNING=1"
        - "alias ll='ls -ltr'"
        - "eval \"$(/opt/homebrew/bin/brew shellenv)\""
        - "export test='hi'"
      become: false

    # Source ~/.bash_profile
    - name: Source ~/.bash_profile
      shell: source ~/{{ executing_user.stdout }}/.bash_profile
      become: false

    # Check if Homebrew is installed
    - name: Check if Homebrew is installed
      command: which brew
      register: brew_check
      failed_when: false
      changed_when: false

    # Install Homebrew if not installed
    - name: Install Homebrew
      shell: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | /bin/bash
      when: brew_check.rc != 0
      become: false

    # Install Casks
    - name: Install Casks
      command:
        cmd: "brew install --cask {{ item }}"
      loop:
        - google-chrome
        - iterm2
        - visual-studio-code
        - dbeaver-community
        - keepassxc
