---
- name: Configure macOS settings
  hosts: localhost
  become: true

  vars:
    cask_apps:
      - google-chrome
      - iterm2
      - visual-studio-code
      - dbeaver-community
      - keepassxc
      - caffeine
    brew_packages:
      - screenfetch
    bash_profile_content: |
      export CLICOLOR=1
      export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
      export PATH="/usr/local/bin:$PATH"
      export BASH_SILENCE_DEPRECATION_WARNING=1
      alias ll='ls -ltr'
      eval "$(/opt/homebrew/bin/brew shellenv)"

  tasks:
    - name: Get executing user's username
      command: whoami
      register: executing_user
      changed_when: false

    - name: Ensure bash is in /etc/shells
      lineinfile:
        path: /etc/shells
        line: '/bin/bash'
        state: present

    - name: Set bash as the default shell for executing user
      command: "chsh -s /bin/bash {{ executing_user.stdout }}"

    # Install Homebrew tasks from another file
    - name: Install Homebrew
      import_tasks: ../tasks/install_homebrew.yml

    - name: Ensure desired contents in ~/.bash_profile
      blockinfile:
        path: "~/.bash_profile"
        block: "{{ bash_profile_content }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      become: false

    - name: Source ~/.bash_profile
      shell: source ~/.bash_profile
      become: false

    - name: Install Casks
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ cask_apps }}"
      become: false

    - name: Install Brew Packages
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_packages }}"
      become: false
